targets:
  $default:
    sources:
      - lib/**
      - res/swaggers/**
      - $package$
      - test/**
    builders:
      drift_dev:
        enabled: true
        generate_for:
          - lib/core/database/**
      chopper_generator:
        enabled: true
        generate_for:
          - lib/core/network/**
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        enabled: true
        options:
          input_folder: "res/swaggers/"
          output_folder: 'lib/core/network/generated/'
          separate_models: true
          overriden_models:
            - file_name: "openHAB"
              import_url: "../overrides/general.dart"
              overriden_models:
                - "StateDescription"
                - "StateOption"
                - "CommandDescription"
                - "CommandOption"