// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_openhab/core/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CommandDescriptionAdapter());
    registerAdapter(CommandOptionAdapter());
    registerAdapter(ItemStateAdapter());
    registerAdapter(SensorHistoryDataBeanAdapter());
    registerAdapter(StateDescriptionAdapter());
    registerAdapter(StateOptionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CommandDescriptionAdapter());
    registerAdapter(CommandOptionAdapter());
    registerAdapter(ItemStateAdapter());
    registerAdapter(SensorHistoryDataBeanAdapter());
    registerAdapter(StateDescriptionAdapter());
    registerAdapter(StateOptionAdapter());
  }
}
