import 'package:flutter/material.dart';
import 'package:flutter_iconpicker/flutter_iconpicker.dart';

const Map<String, IconPickerIcon> iconPackRoom = {
  "house": IconPickerIcon(name: "house", data: Icons.house_outlined, pack: "material"),
  "garden": IconPickerIcon(name: "garden", data: Icons.grass_outlined, pack: "material"),
  "yard": IconPickerIcon(name: "yard", data: Icons.yard_outlined, pack: "material"),
  "diningroom": IconPickerIcon(name: "diningroom", data: Icons.dinner_dining_outlined, pack: "material"),
  "kitchen": IconPickerIcon(name: "kitchen", data: Icons.kitchen_outlined, pack: "material"),
  "livingroom": IconPickerIcon(name: "livingroom", data: Icons.weekend_outlined, pack: "material"),
  "bathroom": IconPickerIcon(name: "bathroom", data: Icons.bathtub_outlined, pack: "material"),
  "toilet": IconPickerIcon(name: "toilet", data: Icons.wc_outlined, pack: "material"),
  "bedroom": IconPickerIcon(name: "bedroom", data: Icons.king_bed_outlined, pack: "material"),
  "kids": IconPickerIcon(name: "kids", data: Icons.child_friendly_outlined, pack: "material"),
  "kidsroom": IconPickerIcon(name: "kidsroom", data: Icons.child_care_outlined, pack: "material"),
  "garage": IconPickerIcon(name: "garage", data: Icons.garage_outlined, pack: "material"),
  "table": IconPickerIcon(name: "table", data: Icons.table_restaurant_outlined, pack: "material"),
  "office": IconPickerIcon(name: "office", data: Icons.computer_outlined, pack: "material"),
  "pool": IconPickerIcon(name: "pool", data: Icons.pool_outlined, pack: "material"),
  "laundry": IconPickerIcon(name: "laundry", data: Icons.local_laundry_service_outlined, pack: "material"),
  "sauna": IconPickerIcon(name: "sauna", data: Icons.spa_outlined, pack: "material"),
  "gym": IconPickerIcon(name: "gym", data: Icons.fitness_center_outlined, pack: "material"),
  "storage": IconPickerIcon(name: "storage", data: Icons.storage_outlined, pack: "material"),
  "balcony": IconPickerIcon(name: "balcony", data: Icons.balcony_outlined, pack: "material"),
  "attic": IconPickerIcon(name: "attic", data: Icons.house_siding_outlined, pack: "material"),
  "roof": IconPickerIcon(name: "roof", data: Icons.roofing_outlined, pack: "material"),
  "window": IconPickerIcon(name: "window", data: Icons.window_outlined, pack: "material"),
  "household": IconPickerIcon(name: "household", data: Icons.cleaning_services_outlined, pack: "material"),
  "coffee": IconPickerIcon(name: "coffee", data: Icons.coffee_outlined, pack: "material"),
  "pets": IconPickerIcon(name: "pets", data: Icons.pets_outlined, pack: "material"),
  "stairs": IconPickerIcon(name: "stairs", data: Icons.stairs_outlined, pack: "material"),
  "hardware": IconPickerIcon(name: "hardware", data: Icons.hardware_outlined, pack: "material"),
  "gaming": IconPickerIcon(name: "gaming", data: Icons.sports_esports_outlined, pack: "material"),
  "wall": IconPickerIcon(name: "wall", data: Icons.wallpaper_outlined, pack: "material"),
};