import 'package:flutter/material.dart';
import 'package:flutter_iconpicker/flutter_iconpicker.dart';

const Map<String, IconPickerIcon> iconPackItems = {
  "switch": IconPickerIcon(name: "switch", data: Icons.power_settings_new_outlined, pack: "material"),
  "lightbulb": IconPickerIcon(name: "lightbulb", data: Icons.lightbulb_outline, pack: "material"),
  "light": IconPickerIcon(name: "light", data: Icons.light_outlined, pack: "material"),
  "lightbulb round": IconPickerIcon(name: "lightbulb round", data: Icons.lightbulb_outline_rounded, pack: "material"),
  "outlet": IconPickerIcon(name: "outlet", data: Icons.power_outlined, pack: "material"),
  "fan": IconPickerIcon(name: "fan", data: Icons.toys_outlined, pack: "material"),
  "heater": IconPickerIcon(name: "heater", data: Icons.heat_pump_outlined, pack: "material"),
  "air conditioner": IconPickerIcon(name: "air conditioner", data: Icons.ac_unit_outlined, pack: "material"),
  "air purifier": IconPickerIcon(name: "air purifier", data: Icons.air_outlined, pack: "material"),
  "humidifier": IconPickerIcon(name: "humidifier", data: Icons.water_damage_outlined, pack: "material"),
  "dehumidifier": IconPickerIcon(name: "dehumidifier", data: Icons.water_damage, pack: "material"),
  "thermostat": IconPickerIcon(name: "thermostat", data: Icons.thermostat_outlined, pack: "material"),
  "door": IconPickerIcon(name: "door", data: Icons.door_back_door_outlined, pack: "material"),
  "window": IconPickerIcon(name: "window", data: Icons.window_outlined, pack: "material"),
  "curtain": IconPickerIcon(name: "curtain", data: Icons.curtains_outlined, pack: "material"),
  "blinds": IconPickerIcon(name: "blinds", data: Icons.blinds_outlined, pack: "material"),
  "shutters": IconPickerIcon(name: "shutters", data: Icons.shutter_speed_outlined, pack: "material"),
  "lock": IconPickerIcon(name: "lock", data: Icons.lock_outline, pack: "material"),
  "garage door": IconPickerIcon(name: "garage door", data: Icons.garage_outlined, pack: "material"),
  "doorbell": IconPickerIcon(name: "doorbell", data: Icons.notifications_active_outlined, pack: "material"),
  "security": IconPickerIcon(name: "security", data: Icons.security_outlined, pack: "material"),
  "camera": IconPickerIcon(name: "camera", data: Icons.camera_alt_outlined, pack: "material"),
  "vacuum": IconPickerIcon(name: "vacuum", data: Icons.cleaning_services_outlined, pack: "material"),
  "mop": IconPickerIcon(name: "mop", data: Icons.water_damage_outlined, pack: "material"),
  "sprinkler": IconPickerIcon(name: "sprinkler", data: Icons.water_damage, pack: "material"),
  "watering can": IconPickerIcon(name: "watering can", data: Icons.water_damage_outlined, pack: "material"),
  "water": IconPickerIcon(name: "water", data: Icons.water_damage, pack: "material"),
  "faucet": IconPickerIcon(name: "faucet", data: Icons.water_damage_outlined, pack: "material"),
  "shower": IconPickerIcon(name: "shower", data: Icons.shower_outlined, pack: "material"),
  "bathtub": IconPickerIcon(name: "bathtub", data: Icons.bathtub_outlined, pack: "material"),
  "toilet": IconPickerIcon(name: "toilet", data: Icons.wc_outlined, pack: "material"),
  "video": IconPickerIcon(name: "video", data: Icons.videocam_outlined, pack: "material"),
  "clock": IconPickerIcon(name: "clock", data: Icons.access_time_outlined, pack: "material"),
  "alarm": IconPickerIcon(name: "alarm", data: Icons.alarm_outlined, pack: "material"),
  "speaker": IconPickerIcon(name: "speaker", data: Icons.speaker_outlined, pack: "material"),
  "tv": IconPickerIcon(name: "tv", data: Icons.tv_outlined, pack: "material"),
  "remote": IconPickerIcon(name: "remote", data: Icons.settings_remote_outlined, pack: "material"),
  "projector": IconPickerIcon(name: "projector", data: Icons.video_label_outlined, pack: "material"),
  "computer": IconPickerIcon(name: "computer", data: Icons.computer_outlined, pack: "material"),
  "phone": IconPickerIcon(name: "phone", data: Icons.phone_outlined, pack: "material"),
  "tablet": IconPickerIcon(name: "tablet", data: Icons.tablet_outlined, pack: "material"),
  "gamepad": IconPickerIcon(name: "gamepad", data: Icons.gamepad_outlined, pack: "material"),
  "headphones": IconPickerIcon(name: "headphones", data: Icons.headphones_outlined, pack: "material"),
  "speaker group": IconPickerIcon(name: "speaker group", data: Icons.speaker_group_outlined, pack: "material"),
  "speaker pair": IconPickerIcon(name: "speaker pair", data: Icons.speaker_outlined, pack: "material"),
  "coffee": IconPickerIcon(name: "coffee", data: Icons.coffee_outlined, pack: "material"),
  "microwave": IconPickerIcon(name: "microwave", data: Icons.microwave_outlined, pack: "material"),
  "fridge": IconPickerIcon(name: "fridge", data: Icons.kitchen_outlined, pack: "material"),
  "trash can": IconPickerIcon(name: "trash can", data: Icons.delete_outline_outlined, pack: "material"),
  "table": IconPickerIcon(name: "table", data: Icons.table_restaurant, pack: "material"),
  "car": IconPickerIcon(name: "car", data: Icons.car_rental_outlined, pack: "material"),
  "bike": IconPickerIcon(name: "bike", data: Icons.directions_bike_outlined, pack: "material"),
  "boat": IconPickerIcon(name: "boat", data: Icons.directions_boat_outlined, pack: "material"),
  "plane": IconPickerIcon(name: "plane", data: Icons.airplanemode_active_outlined, pack: "material"),
  "train": IconPickerIcon(name: "train", data: Icons.train_outlined, pack: "material"),
  "bus": IconPickerIcon(name: "bus", data: Icons.directions_bus_outlined, pack: "material"),
  "motorcycle": IconPickerIcon(name: "motorcycle", data: Icons.motorcycle_outlined, pack: "material"),
  "truck": IconPickerIcon(name: "truck", data: Icons.local_shipping_outlined, pack: "material"),
  "wheelchair": IconPickerIcon(name: "wheelchair", data: Icons.wheelchair_pickup_outlined, pack: "material"),
  "baby": IconPickerIcon(name: "baby", data: Icons.child_care_outlined, pack: "material"),
  "pet": IconPickerIcon(name: "pet", data: Icons.pets_outlined, pack: "material"),
  "plant": IconPickerIcon(name: "plant", data: Icons.eco_outlined, pack: "material"),
  "sun": IconPickerIcon(name: "sun", data: Icons.wb_sunny_outlined, pack: "material"),
  "moon": IconPickerIcon(name: "moon", data: Icons.nights_stay_outlined, pack: "material"),
  "cloud": IconPickerIcon(name: "cloud", data: Icons.cloud_outlined, pack: "material"),
  "snow": IconPickerIcon(name: "snow", data: Icons.ac_unit_outlined, pack: "material"),
  "wind": IconPickerIcon(name: "wind", data: Icons.air_outlined, pack: "material"),
  "fence": IconPickerIcon(name: "fence", data: Icons.fence_outlined, pack: "material"),
  "sensor": IconPickerIcon(name: "sensor", data: Icons.sensors_outlined, pack: "material"),
  "fire": IconPickerIcon(name: "fire", data: Icons.local_fire_department_outlined, pack: "material"),
  "fireplace": IconPickerIcon(name: "fireplace", data: Icons.fireplace_outlined, pack: "material"),
  "smart button": IconPickerIcon(name: "smart button", data: Icons.smart_button, pack: "material"),
  "energy": IconPickerIcon(name: "energy", data: Icons.bolt_outlined, pack: "material"),
  "yard": IconPickerIcon(name: "yard", data: Icons.yard_outlined, pack: "material"),
};