import 'package:flutter/material.dart';

const Map<String, IconData> iconPackItems = {
  "switch": Icons.power_settings_new_outlined,
  "lightbulb": Icons.lightbulb_outline,
  "light": Icons.light_outlined,
  "lightbulb round": Icons.lightbulb_outline_rounded,
  "outlet": Icons.power_outlined,
  "fan": Icons.toys_outlined,
  "heater": Icons.heat_pump_outlined,
  "air conditioner": Icons.ac_unit_outlined,
  "air purifier": Icons.air_outlined,
  "humidifier": Icons.water_damage_outlined,
  "dehumidifier": Icons.water_damage,
  "thermostat": Icons.thermostat_outlined,
  "door": Icons.door_back_door_outlined,
  "window": Icons.window_outlined,
  "curtain": Icons.curtains_outlined,
  "blinds": Icons.blinds_outlined,
  "shutters": Icons.shutter_speed_outlined,
  "lock": Icons.lock_outline,
  "garage door": Icons.garage_outlined,
  "doorbell": Icons.notifications_active_outlined,
  "security": Icons.security_outlined,
  "camera": Icons.camera_alt_outlined,
  "vacuum": Icons.cleaning_services_outlined,
  "mop": Icons.water_damage_outlined,
  "sprinkler": Icons.water_damage,
  "watering can": Icons.water_damage_outlined,
  "water": Icons.water_damage,
  "faucet": Icons.water_damage_outlined,
  "shower": Icons.shower_outlined,
  "bathtub": Icons.bathtub_outlined,
  "toilet": Icons.wc_outlined,
  "video": Icons.videocam_outlined,
  "clock": Icons.access_time_outlined,
  "alarm": Icons.alarm_outlined,
  "speaker": Icons.speaker_outlined,
  "tv": Icons.tv_outlined,
  "remote": Icons.settings_remote_outlined,
  "projector": Icons.video_label_outlined,
  "computer": Icons.computer_outlined,
  "phone": Icons.phone_outlined,
  "tablet": Icons.tablet_outlined,
  "gamepad": Icons.gamepad_outlined,
  "headphones": Icons.headphones_outlined,
  "speaker group": Icons.speaker_group_outlined,
  "speaker pair": Icons.speaker_outlined,
  "coffee": Icons.coffee_outlined,
  "microwave": Icons.microwave_outlined,
  "fridge": Icons.kitchen_outlined,
  "trash can": Icons.delete_outline_outlined,
  "table": Icons.table_restaurant,
  "car": Icons.car_rental_outlined,
  "bike": Icons.directions_bike_outlined,
  "boat": Icons.directions_boat_outlined,
  "plane": Icons.airplanemode_active_outlined,
  "train": Icons.train_outlined,
  "bus": Icons.directions_bus_outlined,
  "motorcycle": Icons.motorcycle_outlined,
  "truck": Icons.local_shipping_outlined,
  "wheelchair": Icons.wheelchair_pickup_outlined,
  "baby": Icons.child_care_outlined,
  "pet": Icons.pets_outlined,
  "plant": Icons.eco_outlined,
  "sun": Icons.wb_sunny_outlined,
  "moon": Icons.nights_stay_outlined,
  "cloud": Icons.cloud_outlined,
  "snow": Icons.ac_unit_outlined,
  "wind": Icons.air_outlined,
  "fence": Icons.fence_outlined,
  "sensor": Icons.sensors_outlined,
  "fire": Icons.local_fire_department_outlined,
  "fireplace": Icons.fireplace_outlined,
  "smart button": Icons.smart_button,
  "energy": Icons.bolt_outlined,
  "yard": Icons.yard_outlined,
};
