import 'package:flutter/material.dart';

const Map<String, IconData> iconPackRoom = {
  "house": Icons.house_outlined,
  "garden": Icons.grass_outlined,
  "yard": Icons.yard_outlined,
  "diningroom": Icons.dinner_dining_outlined,
  "kitchen": Icons.kitchen_outlined,
  "livingroom": Icons.weekend_outlined,
  "bathroom": Icons.bathtub_outlined,
  "toilet": Icons.wc_outlined,
  "bedroom": Icons.king_bed_outlined,
  "kids": Icons.child_friendly_outlined,
  "kidsroom": Icons.child_care_outlined,
  "garage": Icons.garage_outlined,
  "table": Icons.table_restaurant_outlined,
  "office": Icons.computer_outlined,
  "pool": Icons.pool_outlined,
  "laundry": Icons.local_laundry_service_outlined,
  "sauna": Icons.spa_outlined,
  "gym": Icons.fitness_center_outlined,
  "storage": Icons.storage_outlined,
  "balcony": Icons.balcony_outlined,
  "attic": Icons.house_siding_outlined,
  "roof": Icons.roofing_outlined,
  "window": Icons.window_outlined,
  "household": Icons.cleaning_services_outlined,
  "coffee": Icons.coffee_outlined,
  "pets": Icons.pets_outlined,
  "stairs": Icons.stairs_outlined,
  "hardware": Icons.hardware_outlined,
  "gaming": Icons.sports_esports_outlined,
  "wall": Icons.wallpaper_outlined,
};
